# On issue pull request review, if the state is `approved`, this workflow will 
# add a comment into the pull request. If the state is `dismissed`, this workflow
# will remove the comment into the pull request.

name: Pull Request Approved

on:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  approved:
    name: Pull Request Approved
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Add Pull Request Comment
        run: |
          ACCEPT_HEADER="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          CONTENT_HEADER="Content-Type: application/json"
          PR_COMMENT="### Deployment reviewed by ${{ github.event.review.user.login }}"
          PR_PAYLOAD=$(echo '{}' | jq --arg body "$PR_COMMENT" '.body = $body')
          curl -sS -X POST -H "$AUTH_HEADER" -H "$ACCEPT_HEADER" -H "$CONTENT_HEADER" -d "$PR_PAYLOAD" -L ${{ github.event.pull_request.comments_url }} > /dev/null

  dismissed:
    name: Pull Request Dismissed
    if: ${{ github.event.review.state == 'dismissed' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:     
      - name: Remove Pull Request Comment
        run: |
          echo "INFO     | Looking for an existing PR comment."
          ACCEPT_HEADER="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          PR_COMMENT_URI=$(echo ${{ github.event.pull_request.head.repo.issue_comment_url }} | sed "s|{/number}||g")
          curl -sS -H "$AUTH_HEADER" -H "$ACCEPT_HEADER" -L ${{ github.event.pull_request.comments_url }} | jq '.[] | select(.body|test ("### Deployment reviewed by")) | .id' | while read ID; do
            echo "INFO     | Found existing PR comment: $ID. Deleting."
            PR_COMMENT_URL="$PR_COMMENT_URI/$ID"
            echo $PR_COMMENT_URL
            curl -sS -X DELETE -H "$AUTH_HEADER" -H "$ACCEPT_HEADER" "$PR_COMMENT_URL" > /dev/null
          done